### ISSUE TITLE
Fantastic, but a bit slow sometimes

### ISSUE THREAD

**Issue by paolodedo** [gianlucaparadise/telegraf-calendar-telegram#17]
Hello,

I'm in love with this component, so that I switched from node-bot-telegram-api to Telegraph in order to be able to use it.

It was exactly what I was looking for 🗡️ .

But, I noticed sometimes it waits switching from a month to another, why do you think this happens?
It is a behaviour only few times is present, so I was wondering why..

I am available if you need more details.

And... congrats! 💯

**Comment by gianlucaparadise** [comment]
Hi Paolo, thank you 🙏

Unfortunately I'm not maintaining telegram bots anymore, but I'm open to Pull Requests.
