### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by WardenCommander** [gianlucaparadise/telegraf-calendar-telegram#20]
any chance to update telegraf to new 4.7.0 ?

**Comment by gianlucaparadise** [comment]
Unfortunately I'm not maintaining telegram bots anymore, but I'm open to Pull Requests.

**Comment by gianlucaparadise** [comment]
`telegraf-calendar-telegram` v2.0.1 is now supporting Telegraf ^4.8.5
