### ISSUE TITLE
Adding `shortcutButtonsPlacement` option

### ISSUE THREAD

**Issue by mkhoussid** [gianlucaparadise/telegraf-calendar-telegram#30]
I tried to submit a PR, but caught a 403 error.

Anyway, minor - but useful - change:

```diff
--- a/telegraf-calendar-telegram/calendar-helper/index.js
+++ b/telegraf-calendar-telegram/calendar-helper/index.js
@@ -24,6 +24,7 @@ class CalendarHelper {
         maxDate: null,
         ignoreWeekDays: [],
         shortcutButtons: [],
+        shortcutButtonsPlacement: 'top',
         hideIgnoredWeeks: false,
       },
       options
@@ -84,7 +85,9 @@ class CalendarHelper {
       );
     }
 
-    page.push(menuShortcutButtons);
+    page[
+      this.options.shortcutButtonsPlacement === 'bottom' ? 'push' : 'unshift'
+    ](menuShortcutButtons);
   }
 
   addHeader(page, date) {
@@ -209,12 +212,13 @@ class CalendarHelper {
 
     let page = [];
 
+    this.addHeader(page, date);
+    this.addDays(page, date);
+
     const shortcutButtons = this.options.shortcutButtons;
     if (shortcutButtons && shortcutButtons.length > 0) {
       this.addShortcutButtons(page);
     }
-    this.addHeader(page, date);
-    this.addDays(page, date);
 
     return page;
   }
```

This allows to build the calendar like this:

<img width="351" alt="Screenshot 2023-01-25 at 15 51 22" src="https://user-images.githubusercontent.com/44326107/214567998-c2023e26-971b-471b-9512-9875851cb6b2.png">

**Comment by gianlucaparadise** [comment]
Hi! Thank you for your suggestion, but I would like to have it as a PR. When did you had the 403 error? Did you try with a fork PR?

**Comment by mkhoussid** [comment]
> Hi! Thank you for your suggestion, but I would like to have it as a PR. When did you had the 403 error? Did you try with a fork PR?

Well, I cloned the repository locally, checked out into a new branch and tried pushing the changes,

```
$ git checkout -b feature/shortcut-buttons-placement-option
$ git add . && git commit -am 'Added 'shortcutButtonsPlacement' option to CalendarHelper constructor'
$ git push origin feature/shortcut-buttons-placement-option
```
Throws error:

```
remote: Permission to gianlucaparadise/telegraf-calendar-telegram.git denied to mkhoussid.
fatal: unable to access 'https://github.com/gianlucaparadise/telegraf-calendar-telegram.git/': The requested URL returned error: 403
```

<img width="866" alt="Screenshot 2023-01-25 at 23 34 14" src="https://user-images.githubusercontent.com/44326107/214684131-710dd426-610f-4e38-99f4-642a0f92de50.png">

If I'm doing something wrong with creating a PR and there are instructions on how to do so properly, please kindly direct them to me and I'll follow them.

Thanks!

**Comment by gianlucaparadise** [comment]
You should fork first. You need to:
1. click on _Fork_ button on top of this page
2. add your fork remote url to your repo using: `git remote add fork <your-url>`
  * Your url should be something like `https://github.com/mkhoussid/telegraf-calendar-telegram.git`, so your command
3. Push to your fork using: `git push fork feature/shortcut-buttons-placement-option`
4. Then you can open a PR on this repo using your `feature/shortcut-buttons-placement-option` branch as source

**Comment by mkhoussid** [comment]
Cool! PR #31 created, please review
