### ISSUE TITLE
Calendar markup with min and max dates

### ISSUE THREAD

**Issue by machinas-achim** [gianlucaparadise/telegraf-calendar-telegram#4]
Hello there!

I believe that this code:

```
	/**
	 * Return Calendar Markup
	 */
	getCalendar() {
		return this.helper.getCalendarMarkup(new Date());
	}
```

should actually be like this, in order to be able to get correctly (date-limited) markup from the calendar.

```
	/**
	 * Return Calendar Markup
	 */
	getCalendar() {
		return this.helper.getCalendarMarkup(new Date(this.helper.options.minDate));
	}
```

Explanation: the default date ("today") might not be within the restricted range minDate up to maxDate, so the generated markup is potentially showing an erroneous view.

Also note that in this case we also create a temporary Date object that we pass on, because otherwise this.helper.options.minDate will also get changed while generating the markup, similar to this issue https://github.com/gianlucaparadise/telegraf-calendar-telegram/issues/5

**Comment by gianlucaparadise** [comment]
Hi!
Thanks for the suggestion! I preferred to clamp the input date in the `getPage` method to have the closest date as starting date.
You can find this fix in version 1.5.7.
