### ISSUE TITLE
setMinDate and setMaxDate pass by reference

### ISSUE THREAD

**Issue by machinas-achim** [gianlucaparadise/telegraf-calendar-telegram#5]
Another potential improvement:

```
        calendarWidget.setMinDate(myMinDate));
        calendarWidget.setMaxDate(myMaxDate);
```

as per documentation can actually lead to myMinDate and myMaxDate to have their value changed as a side effect when generating a new view. So either make the documentation clearer to pass a completely new (throw-away) object to avoid this:

```
        calendarWidget.setMinDate(new Date(myMinDate));
        calendarWidget.setMaxDate(new Date(myMaxDate));
```

or adjust the setter/getter functions like this:

```
	setMinDate(date) {
		this.helper.setMinDate(new Date(date));
		return this;
	}
```

instead of simply passing the reference to the object as is the case at the moment:

```
		this.helper.setMinDate(date);
```

**Comment by gianlucaparadise** [comment]
Hi!
Thank you for the suggestion! You can find this fix in version 1.5.6.
I preferred to create a new `Date` object.
