### ISSUE TITLE
Remove long time spinners

### ISSUE THREAD

**Issue by fl4x** [gianlucaparadise/telegraf-calendar-telegram#7]
Hi guys!

Thanks for the great add on! I use it in my current project, and here are some enhancement suggestions.

- [x] Add an example how to call it from inline keyboard, with no **infinite spinner**
```javascript
calendar.setDateListener(async (ctx, date) => {
    return await ctx.answerCbQuery()
        .then(async () => {
            return ctx.reply(date)
        })
});
```

- [x]  Add callback handler to **calendar-telegram-ignore** action, it allows to avoid long time spinners:
```javascript
this.bot.action("calendar-telegram-ignore", async context => { 
    return await context.answerCbQuery() 
});
```

- [x]  Add callback handler to **calendar-telegram-next** action:
```javascript
this.bot.action(/calendar-telegram-next-[\d-]+/g, async context => {  // turn function into async
			let dateString = context.match[0].replace("calendar-telegram-next-", "");
			let date = new Date(dateString);
			date.setMonth(date.getMonth() + 1);

			let prevText = context.callbackQuery.message.text;
			return await context.answerCbQuery() // avoid long time spinner
			.then(async () => {
				return context.editMessageText(prevText, this.helper.getCalendarMarkup(date));
			})
		});
```

- [x]  Add callback handler to **calendar-telegram-prev** action:
```javascript
this.bot.action(/calendar-telegram-prev-[\d-]+/g, async context => {  // turn function into async
			let dateString = context.match[0].replace("calendar-telegram-prev-", "");
			let date = new Date(dateString);
			date.setMonth(date.getMonth() - 1);

			let prevText = context.callbackQuery.message.text;
			return await context.answerCbQuery() // avoid long time spinner
			.then(async () => {
				return context.editMessageText(prevText, this.helper.getCalendarMarkup(date));
			})
		});
```

**Comment by gianlucaparadise** [comment]
Hi!
Thank you for the suggestion! I fixed the infinite spinner in the last release (1.5.5).

I didn't know about `context.answerCbQuery` method. Now I use it before calling the date listener callback (https://github.com/gianlucaparadise/telegraf-calendar-telegram/commit/226d6125584d5b4423127e320c77ea32e80c047e#diff-168726dbe96b3ce427e7fedce31bb0bcR21), so you can avoid to use it in your code.
